### ISSUE TITLE
move start button et stop to the left et prefs to the right

### ISSUE THREAD

**Issue by kanadiou** [Rainbox-dev/DuME#133]
perso je préférerais le start tout à gauche avec le pref à droite avec une petit séparation

(gngngn)

**Comment by Nico-Duduf** [comment]
je vais mettre le pref en tout petit tout à droite à coté des boutons "de fenetre" (réduire, maximiser, quitter)

**Comment by Nico-Duduf** [comment]
done

**Comment by kanadiou** [comment]
coeur avec les doigts
