### ISSUE TITLE
set defaut preset

### ISSUE THREAD

**Issue by kanadiou** [Rainbox-dev/DuME#145]
une idée comme ça : 
peut être mettre "set default preset" pour une meilleur compréhension ?

![DuME_1tHiPD2Enq](https://user-images.githubusercontent.com/25553786/72415931-e02d7c00-3775-11ea-9b72-b678f3222c43.png)

**Comment by Nico-Duduf** [comment]
hum...
si décoché oui, mais le meme texte quand décoché

**Comment by Nico-Duduf** [comment]
done
