### ISSUE TITLE
DuME Bugs

### ISSUE THREAD

**Issue by TK55557** [Rainbox-dev/DuME#156]
**Describe the bug**
I couldn't get it to work properly.

I first dragged an AEP file and was unable to export anything. Then I opened After Effects, used the script to send composition to DuME, I always get an alert script "The project must be saved first ... Want to continue?" But the project is already saved, I click on OK and if DuME is already open another new DuME window opens instead of opening the one that is already open. But when you click GO, the render bar starts but does not start. I recorded a video attached to the problem.

The funny thing is that when recording this video I cut and exported it through DuME and it worked, maybe because it was a simple project of just one video, or just a layer on After Effects, I don't know.

[bug_Dume.zip](https://github.com/Rainbox-dev/DuME/files/4338912/bug_Dume.zip)

**Comment by Nico-Duduf** [comment]
That's strange

Can you send me the failing Aep?

Also, after the failed attempt, you can pull the small "keyboard" button under the progress bar to reveal the nerdy stuff
![image](https://user-images.githubusercontent.com/8526542/76786598-c6310980-67b7-11ea-8d3f-2347ac316ec7.png)
Then select the "After Effects Console" tab, copy all its content (Ctrl+A works there) and paste it in a text file to upload it here too
This would help finding what's going wrong.

Thanks!

**Comment by TK55557** [comment]
Hello! analyzing more calmly today, I did 4 tests, first I just drag and drop a file in Dume and sent to render, it gave an error. 

Then I opened the same file in the after and sent it to Dume, it worked! 

Regarding drag and drop, I didn't configure anything in Affter Effects Composition Tab, it was already marked as Encode queue item # 1, and unlike Media Encoder, it doesn't show which compositions the file has to choose one to render. Then I opened the file and saw a composition name. Changing to Encode composition and putting the correct name worked. (But having to open the file just to see the name of the composition, the drag in drop function is kind of useless.)

Third, I opened another file and sent to render, there was an error. Upon opening the AE Console screen, I noticed that one of the errors is about the path of the file "Path is not valid. Path:" D: \ Adobe Cloud \ Creative Cloud Files \ Eale **Caminh) es** \ ... "
Where "**Caminh) es**" should be "**Caminhões**", maybe it is just a problem with the accent.

Attached are the 2 errors and the AEP.

[Dume_bugs.zip](https://github.com/Rainbox-dev/DuME/files/4344021/Dume_bugs.zip)

**Comment by Nico-Duduf** [comment]
I see! many thanks for the feedback, it's very useful.

I'll see if there's a way to list compositions from the project, but I'm not sure it's possible. Only Adobe may be able to do that unfortunately. My way of using DuME is to add the comp I need to render in the render queue in After Effects (and keep it as the first item there), this way DuME finds it and renders it automatically (it picks the first item of the renderqueue by defaullt, but ignores all the render settings, it just use it to find a comp to render).

About the invalid path, it's the accent indeed, I'll fix that in the next update!

**Comment by Nico-Duduf** [comment]
I've created new issues for each problem:

- Path with accent:  #157
- List Ae comps in Dume: #158
