### ISSUE TITLE
DuME crashes rendering AE Project

### ISSUE THREAD

**Issue by saulyance** [Rainbox-dev/DuME#164]
**Describe the bug**
DuME crashes while rendering an AE Project (CC 2020 17.0.6)

**Project File**
https://drive.google.com/open?id=1ItevXLdn0gi6Q7mIiSQ1bapb81Sljlox

**To Reproduce**
1. Send project to render with DuME
2. DuME generates the EXR files on a DuME_Cache folder on my C: Disk (Windows 10)
3. DuME hangs. I can stop the process. If I restart it, it crashes the program and the Cache folder stays there.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/10260739/79483631-2514b900-7fd8-11ea-8d21-2aa2d1322a20.png) Here is DuME 'working' but not working.

**System (please complete the following information):**
 - Version of the OS:  Windows 10 Pro 18362
 - Version of DuME: 0.1.3 RC

**Additional context**
Attaching my project file for testing. Comps for rendering:
Video 01 - Cuadrado
Video 01 - Vertical
Video 02 - Cuadrado
Video 02 - Vertical

**Comment by Nico-Duduf** [comment]
Thanks for your feedback, I'll have a look at that ASAP

**Comment by Nico-Duduf** [comment]
So,

Here the rendering works correctly, except that the cache files should NOT be in C:\ but in the folder defined in the settings of DuME, and should get deleted after the rendering. I'm going to fix this.

I don't know why DuME crashes after the Ae rendering process on your system. How long did you wait before closing it? Maybe it was stuck in some long process...

I'll publish another version which fixes the cache location issue, maybe it will fix your crash too
