### ISSUE TITLE
OGG to WAV convert make .mp4

### ISSUE THREAD

**Issue by Kuzobugi** [Rainbox-dev/DuME#171]
**Describe the bug**
Hi ! I put an ogg music and want it to convert to .wav, it makes me a .mp4

**To Reproduce**
1. I put the OGG in input 1
2. Set up the Wav in All presets
3. Hit render

**Error description, if any**

**Expected behavior**
Expected : have a .wav, I edit the extension file and it workes

**Screenshots**

**System (please complete the following information):**
 - Version of the OS: Win10
 - Version of DuME: 0.1.3

**Additional context**

**Comment by Nico-Duduf** [comment]
Strange!
Thanks for the feedback, I'll fix this for 0.1.4 which should be available soon!

**Comment by Nico-Duduf** [comment]
It's been a long time, sorry, but that's fixed
