### ISSUE TITLE
Problème export webm avec alpha

### ISSUE THREAD

**Issue by Gametalic** [Rainbox-dev/DuME#172]
**Describe the bug**
Impossible de cocher la case "Alpha" dans "Adjust transparency / alpha" dans le cas d'une exportation webm. La case reste vide malgré les clics.
Dans le cas où le codec video "Lossy  : google vp9" est activé, le fait de cliquer sur la case "Alpha" réinitialise l'option du codec en le passant de "Lossy " à "Default". La case 'Alpha" reste bien sûr non coché.
![bugAlphaCase](https://user-images.githubusercontent.com/66310495/83528010-de781100-a4e8-11ea-978c-f0f503506121.gif)

**To Reproduce**
1. Sélectionner Webm dans "All formats"
2. Cocher "Video" 
3. Ajouter l'option 'Adjust transparency / alpha"
4. Ajouter l'option 'Set video codec"
5. Paramètrer le codec sur "Lossy : google vp9" 
6. cliquer sur la case "Alpha" 

**Error description, if any**

**Expected behavior**
Je pensais qu'il était possible de sélectionner l'alpha directement sans devoir préciser le codec. Bon dans tous les cas, même si on le précise, autant que la case alpha fonctionne sans changer les options du codec.

**Screenshots**

**System (please complete the following information):**
 - Version of the OS: windows 10 version 1909
 - Version of DuME: 0.1.3-RC

**Additional context**
J'ai utilisé le script DuME sur AE pour export mes vidéos.

**Comment by Nico-Duduf** [comment]
réparé dans la prochaine version ; Note : l'alpha avec DuME sera supporté en VP8 mais pas VP9.

J'ai ajouté deux presets Webm avec et sans alpha pour simplifier tout ça
