### ISSUE TITLE
"Unable to read VR Path Registery..." error when i try to render an AE file. 

### ISSUE THREAD

**Issue by JFMugen** [Rainbox-dev/DuME#181]
The full error is; 

"Unable to read VR Path Registery from C\Users\USERNAME\Appdata\Local\openvr\openvrpaths.vrpath" 

I tried it on 2 different AE projects. Tried to export as both mp4 and mov. Using CC 2018 (15.1.2x69)

I check the appdata folder, there is not "openvr" folder at all in the Local. 

When I google openvr it shows something about Steam's VR system, which I am not sure it is relevant or not.

I hope this is clear enough. 

(Image that shows error --> https://imgur.com/OlMkJNC)

**Comment by Nico-Duduf** [comment]
will be fixed in the next version, thanks for the feedback

**Comment by Nico-Duduf** [comment]
Note: I think if you let DuME continue the process, the render should actually work (even if the progress bar is not working correctly and DuME seems to be just sitting doing nothing ^^)

**Comment by JFMugen** [comment]
I am pretty sure it does nothing :) It only uses 30mb ram, nothing else. 

(It shows "Ready." at bottom left.)

Anyway, thanks for all the apps you are doing :)
