### ISSUE TITLE
Adding a LUT for encoding

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuME#191]
Feature Request / Question

Will it be possible to encode video and adding a LUT while encoding? There is the possibility to add a LUT in Adobe Media Encoder in the Effects Panel (see screenshot).

This would be helpful to compensate color issues like outlines in this video: https://www.youtube.com/watch?v=t61b6Nk-YPw&amp%3Bfeature=youtu.be

![add-LUT](https://user-images.githubusercontent.com/38455050/102717829-20ca3980-42e5-11eb-9fca-378529a0a447.png)

**Comment by Nico-Duduf** [comment]
I could (and will) quite easily add the ability to use custom LUT in the .cube format, would that suit your need, or are you talking about also including a set of LUTs like AME?

I'd need to see if they're available somewhere and what's the license, or find other interesting LUTs I'd have the right to include

Note to myself: 
the ffmpeg cube command uses video filters:
`-vf lut3d="ARRIP3D65PQ108-33.cube"`

**Comment by Nico-Duduf** [comment]
I could at least add the LUTs used by blender, some of them are very useful

**Comment by reneandritsch** [comment]
Nicolas, there is a LUT from Adobe that can be downloaded to counter the loss of contrast (it is in cube format): https://community.adobe.com/t5/premiere-pro/quot-why-does-my-footage-look-darker-in-premiere-quot-color-q-amp-a/td-p/4788414?page=1

**Comment by Nico-Duduf** [comment]
Done!
I've included the two LUTs from Adobe, and you can pick any other lut in several formats (you'll get the list of available formats in the doc)

**Comment by reneandritsch** [comment]
Thank you so much! I really wonder how you manage to work on all that stuff. Even if your team grew bigger – do you sleep at all ;-)
