### ISSUE TITLE
Add a flag to minize DuME on launch with command line

### ISSUE THREAD

**Issue by adriendurepaire** [Rainbox-dev/DuME#194]
It would be really useful to hide DuME on launch when using it through command line. The flag could be `--min` or `--hide`.

**Comment by Nico-Duduf** [comment]
done!
For now, the splash screen is still shown, but the main window itself is minimized at soon as its built. Tell me if that suits you!

The option is either `--minimize` or `-m`

Available in 0.2.0 soon
