### ISSUE TITLE
When switching to jpg format, the video checkbox is unticked

### ISSUE THREAD

**Issue by Viclio** [Rainbox-dev/DuME#202]
**Describe the bug**
A small issue, nevertheless a bit cumbersome. If jpeg format is chosen, the video checkbox beneath is automaticalley unticked. The user has to tick it again in order to be able to render the sequence.

![image](https://user-images.githubusercontent.com/74590508/104163089-1b4ca480-53f6-11eb-8b22-c3f1d59c87eb.png)

**Comment by Nico-Duduf** [comment]
fixed
