### ISSUE TITLE
Probleme colo depuis after en export QT anim

### ISSUE THREAD

**Issue by kanadiou** [Rainbox-dev/DuME#203]
**Describe the bug**
En lançant un export depuis after, puis en réglant QT animation, l'image ressort plus terne, plus grise.
Souci profil colo ?

Dume v0.1.5

**Comment by Nico-Duduf** [comment]
J'ai complètement refait le color management, tu pourras retester dans la prochaine version (dispo dans quelques jours) !

Il y avait des erreurs de gamma, c'était peut être ça. En tout cas tu devrais avoir les paramètres pour bien régler le truc.
Note : faudra bien vérifier le QT animation, je sais pas quel profil colo il est censé avoir ni quel format de pixel, et c'est pas dit que ffmpeg le sache non plus, auquel cas faudra peut etre qu'on fasse un preset pour mettre les bonnes valeurs (si on trouve ces infos). Bref, on avisera !
