### ISSUE TITLE
Render fails with command line

### ISSUE THREAD

**Issue by adriendurepaire** [Rainbox-dev/DuME#207]
AE rendering fails when we use DuME with command line on one of our PC. A file seems to be created and deleted after the render. The error doesn't seem to be related to preset, comp name, or project file. Here is a basic project, just in case you need it: [Test_DuMe_1610391447129.zip](https://github.com/Rainbox-dev/DuME/files/5837638/Test_DuMe_1610391447129.zip)

Here is a command line example: `"C:\Program Files\DuME-Win\DuME.exe" --comp "Export Dume" --framerate 25 "C:\Users\Adrien du Repaire\AppData\Roaming\MoCode\temp\Test_DuMe_1610391447129.aep" --output "E:\test\Export Dume.gif" --preset "GIF - 450p" --autostart --autoquit`

 - Version of the OS: Win10
 - Version of DuME: 0.1.5

**Comment by Nico-Duduf** [comment]
Bon alors normalement c'est bon, mais je suis pas certain de ce qui posait le souci exactement

ca semble avoir à voir avec le fait qu'il y ait plusieurs versions d'Ae dispo sur le système et que le paramètre ait pas été enregistré correctement

on peut choisir laquelle utiliser dans les settings de Dume via l'UI, 
ou bien dans la commande directement en lançant le truc; `--aerender aerenderpath` mais faut donner le chemin complet de aerender dans ce cas (mon script le fait pour être sûr que les gens essaient pas de rendre un projet 2020 avec 2018 par exemple, comme ca je lance toujours avec la meme version que le ae en cours)

**Comment by adriendurepaire** [comment]
@Nico-Duduf merci, je test ça quand mon collègue qui avait le soucis rentre de vacances. Pas mal `--aerender` ! En plus, vu que je lance le rendu depuis AE, ça me permettra d'être sûr qu'il n'y a pas d'incohérence de versions.

**Comment by Nico-Duduf** [comment]
ouaip c'est pour ça que je l'ai mis ! ça marche bien
