### ISSUE TITLE
First Frame Number 

### ISSUE THREAD

**Issue by Askagraphic** [Rainbox-dev/DuME#225]
**Describe the bug**
Impossible de rentrer un nombre dans le champs de texte "First Frame Number"

**To Reproduce**

1. Add First Frame Number
2. Try modify number
3. fale

**Error description, if any**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Version of the OS: Win 10
 - Version of DuME: 0.2.0

**Additional context**

**Comment by Nico-Duduf** [comment]
Merci, ce sera corrigé dans la prochaine version assez viye

**Comment by Nico-Duduf** [comment]
corrigé dans la prochaine version dispo d'ici quelques jours
